language: node_js
node_js:
  - 11.6.0
cache: npm

install: 
  - npm ci

script:
  - npm test
  - npm run build

deploy:
  provider: release
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master