language: node_js
node_js:
  - 10.15.0
cache: npm

install: 
  - npm install

script:
#   - npm test
  - CI=false npm run build

deploy:
  provider: release
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
