steps:
	# Install
-	name: 'gcr.io/cloud-builders/npm'
	args: ['install']

	# Test
-	name: 'gcr.io/cloud-builders/npm'
	args: ['run', 'test:unit']

	# Test
-	name: 'gcr.io/cloud-builders/npm'
	args: ['run', 'build']

	# Test
-	name: 'gcr.io/$PROJECT_ID/firebase'
	args: ['deploy']